### ISSUE TITLE
mistune? lo qué?

### ISSUE THREAD

**Issue by hugoruscitti** [trifulca/trifulca_foro#1]
Github nos avisa de un problema de seguridad en una de las dependencias, al parecer deberíamos actualizar mistune.

![image](https://user-images.githubusercontent.com/99183/50709629-3639f080-1047-11e9-82f2-b702ff0409b2.png)

Lo que no termino de entender bien es cómo actualizarlo, porque siguiendo las instrucciones de ahí igualmente no puede actualizarlo:

![image](https://user-images.githubusercontent.com/99183/50709695-641f3500-1047-11e9-9a7d-4b45df68d178.png)

¿Es correcto lo que hice?, ¿tuviste que resolver algo así anteriormente @nachopro ?

**Comment by devedetti** [comment]
JAUAJUAJA!!!!

**Comment by hugoruscitti** [comment]
Bueno, lo cierro. Por lo que leí por ahí no es relevante en nuestro proyecto en realidad.
