### ISSUE TITLE
Permitir Upload de imágenes en formato PNG

### ISSUE THREAD

**Issue by hugoruscitti** [trifulca/trifulca_foro#3]
Me llama la atención que el foro no permita subir archivos .png como adjuntos en los post. Solo permite .jpg y gifs...

Viendo el código me encuentro que hay un mensaje hablando de un posible problema de seguridad si se permiten subir archivos .png, ¿habían visto algo así antes?

![trifulca_foro vim 2019-02-16 19-15-08](https://user-images.githubusercontent.com/99183/52905876-6916fd00-321f-11e9-99b2-fb6334c96d81.png)

El link que mencionan es este: https://docs.djangoproject.com/en/1.11/topics/security/#user-uploaded-content

Ahora, mi duda es... ¿tendríamos que permitir subir archivos .png de todas formas?. Para mí es super sorpresivo que el foro no permita subir archivos .png pero esa advertencia me genera dudas... ¿es inseguro en nuestro caso permitir que se suban .png? 

¿que opinan ustedes @nachopro @matagus @iglosiggio ? @

**Comment by iglosiggio** [comment]
> Specifically, an HTML file can be uploaded as an image if that file
contains a valid PNG header followed by malicious HTML. […]. When this file
is subsequently displayed to a user, it **may** be displayed as HTML
depending on the type and configuration of your web server.

Suena demasiado condicional para mí. 🤔

**Comment by devedetti** [comment]
Habilitá el PNG, si nos hackean... nos hackean viejo!
